// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Product.API.Data;

#nullable disable

namespace Product.API.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20231117062018_InitialData")]
    partial class InitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Product.API.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Camera"
                        });
                });

            modelBuilder.Entity("Product.API.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "CP PLUS 3MP Full HD Smart Wi-fi CCTV Home Security Camera | 360° View | 2 Way Talk | Cloud Monitor | Motion Detect | Night Vision | Supports SD Card, Alexa & Ok Google | 15 Mtr, White- CP-E31A",
                            ImageUrl = "https://m.media-amazon.com/images/I/31jX+aam1nL._SL1000_.jpg",
                            Price = 1999m,
                            Title = "CP PLUS 3MP"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "TP-Link Tapo 360° 2MP 1080p Full HD Pan/Tilt Home Security Wi-Fi Smart Camera| Alexa Enabled| 2-Way Audio| Night Vision| Motion Detection| Sound and Light Alarm| Indoor CCTV (Tapo C200) White",
                            ImageUrl = "https://m.media-amazon.com/images/I/41KuE9NipqL._SL1000_.jpg",
                            Price = 2299m,
                            Title = "Tapo"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Fujifilm Instax Mini 12 Instant Camera-Pink",
                            ImageUrl = "https://m.media-amazon.com/images/I/61+5Ld-oc1L._SL1500_.jpg",
                            Price = 6999m,
                            Title = "FUJIFILM"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "ROCKTECH® Action Camera for Vlogging, Mountain Biking,Travelling, Scuba Diving,Motor Vlogging (4K @ 30FPS Action Camera)",
                            ImageUrl = "https://m.media-amazon.com/images/I/51Bp3mZIcZL._SX569_.jpg",
                            Price = 2199m,
                            Title = "Travel Camera"
                        });
                });

            modelBuilder.Entity("Product.API.Entities.Product", b =>
                {
                    b.HasOne("Product.API.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
